version: '3.8' 
 
services: 
  web: 
    build: 
      context: ./web 
      dockerfile: Dockerfile 
    ports: 
      - "8080:80" 
    networks: 
      - my_network 
 
  api: 
    image: httpd:latest 
    ports: 
      - "8081:80" 
    networks: 
      - my_network 
 
networks: 
  my_network: 
    driver: bridge 
